version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node
      - image: circleci/postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: badbunnies
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: badbunnies 
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: yarn
          command: yarn install --check-files
      - run:
          name: db create
          command: bundle exec rake db:create
      - run: 
           name: db load migrate
           command: bundle exec rake db:migrate
  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.7.2-node
      - image: circleci/postgres:12.6
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: reloj_checador_test
          POSTGRES_PASSWORD: badbunnies
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: circleci-demo-ruby
      POSTGRES_PASSWORD: badbunnies 
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: db create
          command: bundle exec rake db:create
      - run:
            name: db create
            command: bundle exec rake db:create
      - run: 
           name: db load migrate
           command: bundle exec rake db:migrate
      # - run:
      #     name: tests
      #     command: bundle exec rspec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build